### PR TITLE
AttributedCharSequenceResultHandler uses Terminal

### LINKED ISSUE #59: Issue in Windows command line when using the help command
When running the Help command in Windows using the `cmd` line, the following Ansi symbols appear. This can't be replicated in Mac or other terminal programs in Windows (for example ConEmu) and is exclusive to the `cmd` line.

qqrxeglzirz_mjmjtxqnbqxuilbiiz6izenrm3lgb2ait05b3hcwg414xsv-gfemkhpoykot1h3zp1wewfvpdauattz37hjfmbvfc2e1bfslemeckbqp-cmbm0bu4pjcm8glsv0ttv6slctpjp1iztvm6j0_-xeo1deoidrkdzd5nng5m9mwg_bdoafaf03bpczknuiqt_gbgwmruk1b

### PR DESCRIPTION
**Pull request by camilojc**
Use Terminal::writer instead of the System.out directly.

Fixes #59

### CODE REVIEW

**Comment by camilojc** [comment]
@ericbottard this is related to the issue I sent you via email that I was seeing in the Windows `cmd` line exclusively.

Of course, this now opens the question, should we avoid using System.out directly throughout the project? And should Shell provide methods to write and read strings to hide the JLine3 Terminal specifics?

**Comment by ericbottard** [comment]
> @ericbottard this is related to the issue I sent you via email that I was seeing in the Windows cmd line exclusively.

Good that this is fixed. Will have a look (although I can't test), but this will work for now

> Of course, this now opens the question, should we avoid using System.out directly throughout the project? And should Shell provide methods to write and read strings to hide the JLine3 Terminal specifics?

I thought about that, especially if we start considering #14. I think the way to go will be to provide `ParameterResolvers` that could pass in a `Writer` (bridging stdout/`Terminal`) and/or a `Reader` (bridging stdin / `Terminal`) for commands that want to interact directly (which they should avoid ideally, leveraging the return value when they can)

**Comment by ericbottard** [comment]
Rebased and merged as a069278, with reworded commit message

**Comment by camilojc** [comment]
> I think the way to go will be to provide ParameterResolvers that could pass in a Writer (bridging stdout/Terminal) and/or a Reader (bridging stdin / Terminal) for commands that want to interact directly (which they should avoid ideally, leveraging the return value when they can)

Right, I see your point.

In addition to this, I think I was thinking one step before the idea you have. As in, how should we provide the `Writer`/`Reader` options to the `ParameterResolver`s & `ResultHandler`s themselves if they require access to these functionalities.

Should the `ParameterResolver`s & `ResultHandler`s be aware of the Terminal and underlying JLine3 implementation?

If the answer is yes, then we can skip the proposal below and just inject the Terminal where required.

If the answer is no:

One option I was thinking about was to add something in these lines to the `Shell` interface:
```java
public PrintWriter getWriter();
public String readLine(String prompt, boolean masked);
```

And, following this, for `ParameterResolver`s for example, we could do either:
1. Inject the `Shell` instance if required by the `ParameterResolver`, or,
1. Provide an extension interface, e.g. `ShellAwareParameterResolver`, that would look something like:

```java
public interface ShellAwareParameterResolver extends ParameterResolver {
    public void initialize(Shell shell);
}
```

Case in hand where this would be useful is for the Interactive resolver (mainly for passwords :) )

For `ResultHandler`s, the same 2 options as for `ParameterResolver`s would follow, either:
1. Inject the Shell instance, or,
1. Update the `ResultHandler` to have an `initialize(Shell shell)` method as most likely all `ResultHandler`s will need access to the Shell to output data.

Didn't want to open an issue yet until we define the step we want to take.

**Comment by ericbottard** [comment]
> Should the ParameterResolvers & ResultHandlers be aware of the Terminal and underlying JLine3 implementation?

Not sure about the resolvers, but for the `ResultHandler`s, I don't see a problem adding a `Writer` parameter to `handleResult()`

**Comment by ericbottard** [comment]
Realized that `AttributedCharSequenceResultHandler` already needs the `Terminal` to do ansi escaping anyway...

**Pull request closed without merging**
